'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { BookOpen, Shield, Sparkles, BarChart3 } from 'lucide-react';
import { createSupabaseBrowserClient } from '@/lib/supabase';
import { Footer } from '@/components/layout/Footer';

export default function HomePage(): JSX.Element {
  const [isAuthenticated, setIsAuthenticated] = useState<boolean | null>(null);

  useEffect(() => {
    const checkAuth = async () => {
      try {
        const supabase = createSupabaseBrowserClient();
        const { data: { user } } = await supabase.auth.getUser();
        setIsAuthenticated(!!user);
      } catch (error) {
        setIsAuthenticated(false);
      }
    };
    checkAuth();
  }, []);

  return (
    <main className="flex min-h-screen flex-col">
      {/* Header */}
      <header className="border-b">
        <div className="container mx-auto px-4 py-4 flex items-center justify-end">
          <div className="flex gap-4">
            {!isAuthenticated && (
              <>
                <Link href="/login">
                  <Button variant="ghost">Sign In</Button>
                </Link>
                <Link href="/signup">
                  <Button>Sign Up</Button>
                </Link>
              </>
            )}
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="flex-1 flex items-center justify-center p-8">
        <div className="container mx-auto max-w-4xl text-center space-y-8">
          <div className="space-y-4">
            <h1 className="text-7xl md:text-8xl font-bold tracking-tight text-primary">
              Reflect AI
            </h1>
            <h2 className="text-3xl md:text-4xl font-semibold tracking-tight">
              Your AI-Powered Journaling Companion
            </h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Maintain consistent journaling habits with intelligent AI assistance.
              Privacy-first design ensures your thoughts stay yours.
            </p>
          </div>

          <div className="flex gap-4 justify-center pt-4">
            {isAuthenticated ? (
              <Link href="/write">
                <Button size="lg" className="text-lg px-8">
                  Start Journaling
                </Button>
              </Link>
            ) : (
              <Link href="/signup">
                <Button size="lg" className="text-lg px-8">
                  Start Journaling
                </Button>
              </Link>
            )}
          </div>

          {/* Hero Image */}
          <div className="relative w-full max-w-4xl mx-auto mt-12 mb-8">
            <div className="aspect-video rounded-lg overflow-hidden">
              <Image
                src="/Landing_page_image.png"
                alt="Reflect AI - AI-Powered Journaling"
                width={1200}
                height={675}
                className="rounded-lg object-cover w-full h-full"
                priority
              />
            </div>
          </div>

          {/* Features */}
          <div className="grid md:grid-cols-3 gap-6 pt-16">
            <Card>
              <CardHeader>
                <Sparkles className="h-8 w-8 text-primary mb-2" />
                <CardTitle>AI-Powered Prompts</CardTitle>
                <CardDescription>
                  Get context-aware journaling prompts generated by Claude AI
                </CardDescription>
              </CardHeader>
            </Card>
            <Card>
              <CardHeader>
                <BarChart3 className="h-8 w-8 text-primary mb-2" />
                <CardTitle>Sentiment Analysis</CardTitle>
                <CardDescription>
                  Track your emotional patterns with local sentiment analysis
                </CardDescription>
              </CardHeader>
            </Card>
            <Card>
              <CardHeader>
                <Shield className="h-8 w-8 text-primary mb-2" />
                <CardTitle>Privacy First</CardTitle>
                <CardDescription>
                  PII masking ensures your personal information stays private
                </CardDescription>
              </CardHeader>
            </Card>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
